load("@python_versions//3.12:defs.bzl", compile_pip_requirements_3_12 = "compile_pip_requirements")

compile_pip_requirements_3_12(
    name = "requirements_3_12",
    src = "requirements.in",
    requirements_txt = "requirements_lock_3_12.txt",
)
